# Generated by Django 3.2.5 on 2021-07-11 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pythons_app', '0002_alter_python_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='python',
            name='image',
        ),
    ]
