# Generated by Django 3.2.5 on 2021-07-11 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pythons_app', '0003_remove_python_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='python',
            name='image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
