# Generated by Django 3.2.5 on 2021-07-29 06:43

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pythons_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='pythonsuser',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
